name: weather_pipe
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - pyyaml
  - numpy
  - scikit-learn
  - lightgbm
  - xgboost
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1